# Generated by Django 4.2.1 on 2023-05-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='img',
            field=models.CharField(max_length=200, null=True, verbose_name='Адрес фото'),
        ),
    ]
